# This file specifices the services used on render.com to deploy the app
previewsEnabled: true
previewsExpireAfterDays: 3

services:
  - type: web
    name: render-env-test
    plan: starter
    previewPlan: starter
    env: node
    initialDeployHook: yarn db:seed
    healthCheckPath: /
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ASDF
        fromGroup: "render-shared"
        sync: false
